
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useEgacyDate
    username: postgres
    password: 1234567
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    propertis:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace